### ISSUE TITLE
[integration] Messaging Errors

### ISSUE THREAD

**Issue by LayneHaber** [connext/nxtp#214]
Occasionally messaging errors will be thrown from the sdk. Hard to reproduce, but can be seen locally intermittently. Not clear what the error is, though it does clear up after a restart of the docker services

**Comment by LayneHaber** [comment]
logs:

```
[1629140192662] ERROR (30199 on MacBook-Pro.local): Fulfilling failed
    transactionId: "0xa749dd93281b987630f5ff15f9afea1df71ebc752fae09a24b76a90a7d249f7b"
    error: {
      "message": "Messaging error",
      "context": {
        "method": "finishTransfer",
        "methodId": "0x0dd7f7d3cc251173f1f95b8a3c957d113894b26d605a9075b249982404c5a9e7",
        "transactionId": "0xa749dd93281b987630f5ff15f9afea1df71ebc752fae09a24b76a90a7d249f7b",
        "messagingError": {
          "message": "Request failed with status code 500",
          "type": "Error",
          "context": {},
          "stack":
              Error: Request failed with status code 500
                  at createError (/Users/laynehaber/Developer/nxtp/node_modules/axios/lib/core/createError.js:16:15)
                  at settle (/Users/laynehaber/Developer/nxtp/node_modules/axios/lib/core/settle.js:17:12)
                  at IncomingMessage.handleStreamEnd (/Users/laynehaber/Developer/nxtp/node_modules/axios/lib/adapters/http.js:260:11)
                  at IncomingMessage.emit (events.js:412:35)
                  at IncomingMessage.emit (domain.js:470:12)
                  at endReadableNT (internal/streams/readable.js:1317:12)
                  at processTicksAndRejections (internal/process/task_queues.js:82:21)
        }
      }
```

**Comment by LayneHaber** [comment]
Seems like it could be coming from the auth:

```
{"level":50,"time":1629141537448,"pid":19,"hostname":"f3fc8d320eca","reqId":"req-8e","req":{"method":"POST","url":"/auth","hostname":"localhost:5040","remoteAddress":"172.21.0.1","remotePort":58784},"res":{"statusCode":500},"err":{"type":"Error","message":"Verification failed, expected 0x0d1d4e623D10F9FBA5Db95830F7d3839406C6AF2, got 0xDa511857A0dc6d5b5813e07D01EFAEBE4a1C6E98","stack":"Error: Verification failed, expected 0x0d1d4e623D10F9FBA5Db95830F7d3839406C6AF2, got 0xDa511857A0dc6d5b5813e07D01EFAEBE4a1C6E98\n    at MessagingAuthService.<anonymous> (/app/dist/auth/messaging-auth-service.js:51:23)\n    at Generator.next (<anonymous>)\n    at /app/dist/auth/messaging-auth-service.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/dist/auth/messaging-auth-service.js:4:12)\n    at MessagingAuthService.verifyAndVend (/app/dist/auth/messaging-auth-service.js:40:16)\n    at /app/dist/index.js:44:42\n    at Generator.next (<anonymous>)\n    at /app/dist/index.js:8:71\n    at new Promise (<anonymous>)"},"msg":"Verification failed, expected 0x0d1d4e623D10F9FBA5Db95830F7d3839406C6AF2, got 0xDa511857A0dc6d5b5813e07D01EFAEBE4a1C6E98"}
```

**Comment by jakekidd** [comment]
> Error: Verification failed, expected 0x0d1d4e623D10F9FBA5Db95830F7d3839406C6AF2, got 0xDa511857A0dc6d5b5813e07D01EFAEBE4a1C6E98

Hmm. Would this really result in a 500 error, though?

**Comment by jakekidd** [comment]
Is this a token refresh issue?

**Comment by rhlsthrm** [comment]
https://github.com/connext/nats-auth/blob/main/src/index.ts#L56

This is the correct code. And you are correct it does not do anything so it is a 500 error, which we should probably change.

**Comment by LayneHaber** [comment]
Update: This likely comes from calling `connect` on messaging more than once. This is solved in #237
