### ISSUE TITLE
[router] Txs not cancelling when lack of relayer fee

### ISSUE THREAD

**Issue by rhlsthrm** [connext/nxtp#682]
Polygon -> ETH transfer of ETH, keeps trying to prepare but fails:

```
{"level":50,"time":1640763212434,"pid":1,"hostname":"07b8f09147a5","name":"0x29A519e21d6A97cdB82270b69c98bAc6426CDCf9","requestContext":{"id":"PmPITxPDS6ucXeYe6872Cg/38959306","origin":"subscribeToMetaTxRequest","transactionId":"0x5b148f3c1d089bd310f3d39dfb80bb25784f4f80baef8486cf8cfc4ab23737f8"},"methodContext":{"id":"PmPITxPDS6ucXeYe6872Cg/38959305","name":"subscribeToMetaTxRequest"},"error":{"message":"Transaction would fail on chain.","context":{"message":"execution reverted: Address: insufficient balance","chainError":{"code":"SERVER_ERROR","reason":"processing response error","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d416464726573733a20696e73756666696369656e742062616c616e6365000000"}},"type":"TransactionReverted","stack":"Error: Transaction would fail on chain.\n    at Object.parseError (/home/node/node_modules/@connext/nxtp-txservice/dist/shared/errors.js:346:16)\n    at /home/node/node_modules/@connext/nxtp-txservice/dist/shared/syncProvider.js:103:52\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"},"msg":"Error executing metatx request"}
```

**Comment by rhlsthrm** [comment]
This was because of lack of relayer fee. We need to block auctions and cancel when this happens.
